#include "syntacticParser.h"

bool semanticParse();
bool semanticParseCLEAR();
bool semanticParseCROSS();
bool semanticParseCROSSTRANSPOSE();
bool semanticParseDISTINCT();
bool semanticParseEXPORT();
bool semanticParseEXPORTMATRIX();
bool semanticParseINDEX();
bool semanticParseJOIN();
bool semanticParseNESTEDJOIN();
bool semanticParsePARTHASHJOIN();
bool semanticParseLIST();
bool semanticParseLOAD();
bool semanticParseLOADMATRIX();
bool semanticParsePRINT();
bool semanticParsePRINTMATRIX();
bool semanticParsePROJECTION();
bool semanticParseRENAME();
bool semanticParseSELECTION();
bool semanticParseSORT();
bool semanticParseSOURCE();
bool semanticParseGROUPBY();